/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BottomNav: typeof import('./src/components/BottomNav.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MainBanner: typeof import('./src/components/MainBanner.vue')['default']
    MainMenu: typeof import('./src/components/MainMenu.vue')['default']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NIcon: typeof import('naive-ui')['NIcon']
    NProgress: typeof import('naive-ui')['NProgress']
    PlaylistDetail: typeof import('./src/components/PlaylistDetail.vue')['default']
    RandomPlaylist: typeof import('./src/components/RandomPlaylist.vue')['default']
    RandomSong: typeof import('./src/components/RandomSong.vue')['default']
    RecommendedPlaylist: typeof import('./src/components/RecommendedPlaylist.vue')['default']
    RecommendedSong: typeof import('./src/components/RecommendedSong.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    Song: typeof import('./src/components/Song.vue')['default']
    SongPlay: typeof import('./src/components/SongPlay.vue')['default']
    TopNav: typeof import('./src/components/TopNav.vue')['default']
  }
}
